name: Graves
version: 0.0.1-beta1
main: mc.graves.PluginMain
api-version: 1.20
softdepend:
  - Compendium

#

commands:
  graves:
    description: ''
    usage: 'please use /graves to show help'

  #

  bury:
    description: 'Allows to bury yourself or another player.'
    usage: '/bury | /bury <player>'

#

permissions:
  mc.graves.*:
    description: ''
    children:
      mc.graves.commands.*: true
      mc.graves.bury.*: true

  #

  mc.graves.commands.*:
    description: ''
    children:
      mc.graves.commands.graves.*: true

  #

  mc.graves.commands.graves.*:
    description: ''
    children:
      mc.graves.commands.graves.reload-config: true
      mc.graves.commands.graves.bury.*: true

  #

  mc.graves.commands.graves.reload-config:
    description: 'Allows to reload plugin config.'
    default: false

  #

  mc.graves.commands.graves.bury.*:
    description: ''
    children:
      mc.graves.commands.graves.bury.self: true
      mc.graves.commands.graves.bury.others: true

  mc.graves.commands.graves.bury.self:
    description: 'Allows you to bury yourself.'
    default: false

  mc.graves.commands.graves.bury.others:
    description: 'Allows you to bury someone else.'
    default: false

  #

  mc.graves.bury.*:
    description: ''
    children:
      mc.graves.bury.self: true

  mc.graves.bury.self:
    description: 'Allows you to be buried at your death.'
    default: false